name: server测试

on: push

jobs:
  Run_instance:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: 数据库
      uses: installer/setup-mysql@v1
      with:
        mysql-version: '8.0' # 指定MySQL版本
        server-type: 'mysql-server'
        port: '3306'
        allow-remote-access: 'true'
        root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # 设置MySQL root用户的密码
        custom-mysql-conf: |
          [mysqld]
          bind-address = 0.0.0.0
          port = 3306
          # 其他自定义配置
    - name: Connect to MySQL
      run: mysql -u root -p$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"

    - name: build
      run: sh ./build.sh
    - name: 启动server
      run: ./server
    - name: 浏览器端
      run: ip:9006
