name: server测试

on: push

jobs:
  Run_instance:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    # - name: 数据库
    #   uses: mirromutth/mysql-action@v1.1
    #   with:
    #     host port: 9006
    #     container port: 9006
    #     character set server: 'utf8' 
    #     mysql version: '8.0'
    #     mysql database: 'yourdb' 
    #     mysql root password: root 
    #     mysql user: root
    #     mysql password: root


    - name: build
      run: sh ./build.sh
    - name: 启动server
      run: ./server
    - name: 浏览器端
      run: ip:9006
