name: server测试

on: push

jobs:
  Run_instance:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 数据库
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
    - run: mysql -uroot -e 'SELECT version()'


    - name: build
      run: sh ./build.sh
    # - name: 启动server
    #   run: ./server
    - name: 浏览器端
      run: ip:9006
