name: server测试

on: push

jobs:
  Run_instance:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 数据库
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
        # my-cnf: |
        #   innodb_log_file_size=256MB
        #   innodb_buffer_pool_size=512MB
        #   max_allowed_packet=16MB
        #   max_connections=50
        #   local_infile=1
        # auto-start: true
        # # root-password: root
        # user: ll
        # password: ll
        
    - name: 555
      run: mysql -uroot -e 'SELECT version()'

    - name: 111
      run: mysql -u 11 -p 11 -e "show databases;"
    - name: ...
      run: mysql -u ll -pll
    - name: 111
      run: mysql -e "show databases;"

    # - name: build
    #   run: sh ./build.sh

    # - name: 启动server
    #   run: ./server
    # - name: 浏览器端
    #   run: curl http://ip:9006
