name: server测试

on: push

jobs:
  Run_instance:
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 数据库
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: "8.0"
        auto-start: true
        root-password: "root"

    - name: 1
      run: mysql -uroot -proot -e 'create database yourdb;'
    - name: 2
      run: mysql -uroot -proot -e "USE yourdb;CREATE TABLE user(username char(50) NULL,passwd char(50) NULL)ENGINE=InnoDB;"
    - name: 3
      run: mysql -uroot -proot -e "USE yourdb;INSERT INTO user(username, passwd) VALUES('name', 'passwd');"
    - name: 4
      run: mysql -uroot -proot -e 'USE yourdb;show tables;'

    - name: build
      run: sh ./build.sh

    - name: 启动server
      run: ./server
    - name: 浏览器端
      run: curl http://ip:9006
